CONFIG += no_fixpath
QT = core gui widgets
CONFIG += no_fixpath
QT = core gui widgets
CONFIG += no_fixpath
QT = core gui widgets
CONFIG += no_fixpath
QT = core gui widgets multimedia multimediawidgets
CONFIG += no_fixpath
QT = core gui widgets multimedia multimediawidgets
